### ISSUE TITLE
automating casts like checking todos

### ISSUE THREAD

**Issue by mschaaf** [charlespwd/habitica-cli#2]
It would be nice to be able to casts spells similar to checking todos.
e.g. cast "Burst of Flames"  TODO 1

**Comment by charlespwd** [comment]
Good idea! I'll look into it.

**Comment by charlespwd** [comment]
fixed by c043d5ca3627add03bd5e5546fd108ca087d1bb3

**Comment by mschaaf** [comment]
thanks. nice.

**Comment by charlespwd** [comment]
It's in the latest version (1.5.0) enjoy :)
